### PR TITLE
fix(blevm): support multiple proof aggregation

### LINKED ISSUE #148: blevm aggregator: range proof specs
Currently blevm aggregator proves two adjancent blocks. We need to to extend this to the range we want to prove from evm-prover. There are a couple of ways to do this:

### iterate

We can simply extend the current aggregator to read a variable number of proofs and match each adjacent header hash. The variable number can be the first input to the program should be at least 2. This is the easiest to implement but it scales linearly with the number of blocks and is not parallellisable.

### tree

We can turn the range into a binary, ternary, or 4-ary tree where each proof is a leaf node and they are pairwise aggregated into intermediate nodes until a root node remains. It is parallelisable and scales lograrithmically with number of blocks.

###  merge

We can split the range into left and right halves and recursively combine them, the base case being two adjacent blocks. When merging we can ensure continuity in the header hash. It is parallelisable and scales logarithmically with the number of blocks.

I think it's easiest to start with the iterative approach. If we want to optimize we can switch to the merge approach.

### PR DESCRIPTION
**Pull request by tuxcanfly**
## Overview

Fixes #148 Implements multiple proof aggregation by iterating over the range. Extends `blevm-aggregator` for variable number of proofs. Also adds helpers to `blevm-prover` so that the library can be used to generate range proofs.

### CODE REVIEW

File: provers/blevm/blevm-prover/src/lib.rs [hunk 1]
```diff
@@ -237,13 +252,88 @@ impl BlockProver {
...
+    pub vk: SP1VerifyingKey,
+}
+
+/// Output from proof aggregation
+pub struct AggregationOutput {
+    /// The aggregated proof
+    pub proof: SP1ProofWithPublicValues,
+}
+
+impl BlockProver {
```
Comment (ninabarbakadze) [inline provers/blevm/blevm-prover/src/lib.rs:280]: should this have its own file?

File: provers/blevm/script/src/bin/main.rs [hunk 2]
```diff
@@ -22,6 +24,7 @@ use std::{error::Error, fs};
 
 pub const BLEVM_ELF: &[u8] = include_elf!("blevm");
 pub const BLEVM_MOCK_ELF: &[u8] = include_elf!("blevm-mock");
+pub const BLEVM_AGGREGATOR_ELF: &[u8] = include_elf!("blevm-aggregator");
```
Comment (ninabarbakadze) [inline provers/blevm/script/src/bin/main.rs:27]: where is blevm-aggregator compiled?

**Review by rootulp — APPROVED** [review]
LGTM, great work

**Comment by rootulp** [comment]
Note: CI is failing

File: provers/blevm/script/src/bin/main.rs (hunk 2 above)
Comment (tuxcanfly) [reply provers/blevm/script/src/bin/main.rs:27]: Fixed.

File: provers/blevm/blevm-prover/src/lib.rs (hunk 1 above)
Comment (tuxcanfly) [reply provers/blevm/blevm-prover/src/lib.rs]: Moved proof helpers to their own file.

**Review by rootulp — APPROVED** [review]
